version: "3"
services:
  ignite:
    image: apacheignite/ignite:2.1.0
    container_name: apache_ignite
    environment:
      - CONFIG_URI=https://raw.githubusercontent.com/itfobos/ignite/prod_assembly/ignite-ws/conf/ignite-config.xml
      - IGNITE_QUIET=false

  ignite-ws:
      image: turukin/ignite-ws:0.1
      container_name: ignite-ws
      environment:
        - CONFIG_URI=https://raw.githubusercontent.com/itfobos/ignite/prod_assembly/ignite-ws/conf/ignite-config.xml
      ports:
        - "9000:9000"
