version: "3"
services:
  ignite:
    image: apacheignite/ignite
    container_name: apache_ignite
    environment:
      - OPTION_LIBS=ignite-rest-http
      - CONFIG_URI=https://raw.githubusercontent.com/itfobos/ignite/master/ignite-ws/conf/example-default.xml
      - IGNITE_QUIET=false

    network_mode: host