version: "3"
services:
  ignite:
    image: apacheignite/ignite
    container_name: apache_ignite
    environment:
      - CONFIG_URI=https://raw.githubusercontent.com/itfobos/ignite/master/ignite-ws/conf/ignite-config.xml
      - IGNITE_QUIET=false

    volumes:
      #(HOST_PATH:CONTAINER_PATH).
       - ./logs/ignite:/opt/ignite/apache-ignite-fabric-2.1.0-bin/work/log/

    network_mode: host