# TODO:
version: "3"
services:
  ignite:
    image: apacheignite/ignite
    container_name: apache_ignite
    environment:
      - CONFIG_URI=https://raw.githubusercontent.com/itfobos/ignite/prod_assembly/ignite-ws/conf/ignite-config.xml
      - IGNITE_QUIET=false

    network_mode: host